language: node_js
node_js:
  - 6
  - 8
  - 9
addons:
  code_climate:
    repo_token: a7347be167f83e8245e740898164e9c0c1cbb6e76237dbe17ad8f4b4f4120924
after_success:
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < lcov.info
